[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "ExpandedHUD"
description = "Enhanced HUD displaying weapon stats, damage meter with DPS tracking, and real-time speedometer for improved gameplay awareness."
websiteUrl = "https://github.com/Little-Sparroh/ExpandedHUD"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/ExpandedHUD.dll"
target = "BepInEx/plugins/ExpandedHUD.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]
